export const cableProviders = [
  { label: 'DSTV', value: 'dstv' },
  { label: 'GoTV', value: 'gotv' },
  { label: 'Startimes', value: 'startimes' },
]

export const cableVariations = {
  dstv: [
    { variation_code: 'dstv-padi', name: 'DStv Padi', variation_amount: '1850.00' },
    { variation_code: 'dstv-yanga', name: 'DStv Yanga', variation_amount: '2565.00' },
    { variation_code: 'dstv-confam', name: 'DStv Confam', variation_amount: '4615.00' },
    { variation_code: 'dstv79', name: 'DStv Compact', variation_amount: '7900.00' },
    { variation_code: 'dstv7', name: 'DStv Compact Plus', variation_amount: '12400.00' },
    { variation_code: 'dstv3', name: 'DStv Premium', variation_amount: '18400.00' },
    { variation_code: 'dstv6', name: 'DStv Asia', variation_amount: '6200.00' },
    { variation_code: 'dstv9', name: 'DStv Premium French', variation_amount: '25550.00' },
    { variation_code: 'dstv-access-1', name: 'DStv Access', variation_amount: '2000.00' },
    { variation_code: 'dstv-family-1', name: 'DStv Family', variation_amount: '4000.00' },
    { variation_code: 'dstv-mobile-1', name: 'DSTV Mobile', variation_amount: '790.00' },
    { variation_code: 'dstv30', name: 'DStv Compact + Extra View', variation_amount: '10400.00' },
    { variation_code: 'dstv33', name: 'DStv Premium Extra View', variation_amount: '20900.00' },
    { variation_code: 'showmax3500', name: 'Showmax Standalone', variation_amount: '3500.00' },
  ],
  gotv: [
    { variation_code: 'gotv-lite', name: 'GOtv Lite', variation_amount: '410.00' },
    { variation_code: 'gotv-jinja', name: 'GOtv Jinja', variation_amount: '1640.00' },
    { variation_code: 'gotv-jolli', name: 'GOtv Jolli', variation_amount: '2460.00' },
    { variation_code: 'gotv-max', name: 'GOtv Max', variation_amount: '3600.00' },
    { variation_code: 'gotv-supa-plus', name: 'GOtv Supa Plus', variation_amount: '15700.00' },
    { variation_code: 'gotv-lite-3months', name: 'GOtv Lite (3 Months)', variation_amount: '1080.00' },
    { variation_code: 'gotv-lite-1year', name: 'GOtv Lite (1 Year)', variation_amount: '3180.00' },
  ],
  startimes: [
    { variation_code: 'nova', name: 'Nova - 1 Month', variation_amount: '900.00' },
    { variation_code: 'basic', name: 'Basic - 1 Month', variation_amount: '1700.00' },
    { variation_code: 'smart', name: 'Smart - 1 Month', variation_amount: '2200.00' },
    { variation_code: 'classic', name: 'Classic - 1 Month', variation_amount: '2500.00' },
    { variation_code: 'super', name: 'Super - 1 Month', variation_amount: '4200.00' },
    { variation_code: 'nova-weekly', name: 'Nova - 1 Week', variation_amount: '300.00' },
    { variation_code: 'basic-weekly', name: 'Basic - 1 Week', variation_amount: '600.00' },
    { variation_code: 'smart-weekly', name: 'Smart - 1 Week', variation_amount: '700.00' },
    { variation_code: 'classic-weekly', name: 'Classic - 1 Week', variation_amount: '1200.00' },
    { variation_code: 'super-weekly', name: 'Super - 1 Week', variation_amount: '1500.00' },
    { variation_code: 'nova-daily', name: 'Nova - 1 Day', variation_amount: '90.00' },
    { variation_code: 'basic-daily', name: 'Basic - 1 Day', variation_amount: '160.00' },
    { variation_code: 'smart-daily', name: 'Smart - 1 Day', variation_amount: '200.00' },
    { variation_code: 'classic-daily', name: 'Classic - 1 Day', variation_amount: '320.00' },
    { variation_code: 'super-daily', name: 'Super - 1 Day', variation_amount: '400.00' },
  ],
}